%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-nav2-minimal-tb3-sim
Version:        1.1.0
Release:        3%{?dist}%{?release_suffix}
Summary:        ROS nav2_minimal_tb3_sim package

License:        Apache 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-robot-state-publisher
Requires:       ros-kilted-ros-gz-bridge
Requires:       ros-kilted-ros-gz-image
Requires:       ros-kilted-ros-gz-interfaces
Requires:       ros-kilted-ros-gz-sim
Requires:       ros-kilted-xacro
Requires:       ros-kilted-ros-workspace
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-robot-state-publisher
BuildRequires:  ros-kilted-ros-gz-bridge
BuildRequires:  ros-kilted-ros-gz-image
BuildRequires:  ros-kilted-ros-gz-interfaces
BuildRequires:  ros-kilted-ros-gz-sim
BuildRequires:  ros-kilted-xacro
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-lint-auto
BuildRequires:  ros-kilted-ament-lint-common
%endif

%description
Nav2 Minimum TurtleBot3 Simulation

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Apr 22 2025 Steve Macenski <steve@opennav.org> - 1.1.0-3
- Autogenerated by Bloom

* Tue Apr 15 2025 Steve Macenski <steve@opennav.org> - 1.1.0-2
- Autogenerated by Bloom

* Tue Apr 15 2025 Steve Macenski <steve@opennav.org> - 1.1.0-1
- Autogenerated by Bloom

* Mon Jan 06 2025 Steve Macenski <steve@opennav.org> - 1.0.2-1
- Autogenerated by Bloom

* Fri Jun 21 2024 Steve Macenski <steve@opennav.org> - 1.0.1-1
- Autogenerated by Bloom

* Wed Jun 05 2024 Steve Macenski <steve@opennav.org> - 1.0.0-1
- Autogenerated by Bloom

